# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: cifar.yaml
  - model: cifar.yaml
  - paths: default.yaml
  - trainer: default.yaml

task_name: "train"

train: True

test: True

compile: False

# simply provide checkpoint path to resume training
ckpt_path: /opt/model_checkpoint.pth

# seed for random number generators in pytorch, numpy and python.random
seed: 23